apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: issuers
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/prod/infra/issuers
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager
