apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  releaseName: traefik
  targetNamespace: ingress
  chart:
    spec:
      chart: traefik
      version: 28.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik-official
        namespace: flux-system
      interval: 12h
  interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 3
  # Reference values from traefik-values.yaml
  # See infra/ingress/traefik-values.yaml
  values:
