---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - secret-slack-webhook.yaml
  - provider-slack.yaml
  - alert-helm.yaml
  - alert-kustomize.yaml
